# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=24, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('content', models.TextField(blank=True, max_length=256, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
